# Generated by Django 5.1.7 on 2025-04-01 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20250401_0717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='postcategory',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='postcategory',
            old_name='post_id',
            new_name='post',
        ),
    ]
